export const initSurvey = {
	user: {
		user_name: '',
		org_name: '',
		dept_name: '',
		email: '',
		skills: {
			confidence: { department: 0, organization: 0, self: 0 },
			'people management': { department: 0, organization: 0, self: 0 },
			accountability: { department: 0, organization: 0, self: 0 },
			prioritization: { department: 0, organization: 0, self: 0 },
			'motivational skills': { department: 0, organization: 0, self: 0 },
			coaching: { department: 0, organization: 0, self: 0 },
			'project management': { department: 0, organization: 0, self: 0 },
			'analytical skills': { department: 0, organization: 0, self: 0 },
			creativity: { department: 0, organization: 0, self: 0 },
			mentorship: { department: 0, organization: 0, self: 0 },
			'inspirational abilities': { department: 0, organization: 0, self: 0 },
			'goal setting': { department: 0, organization: 0, self: 0 },
			'stress management': { department: 0, organization: 0, self: 0 },
			politeness: { department: 0, organization: 0, self: 0 },
			cooperation: { department: 0, organization: 0, self: 0 },
			reliability: { department: 0, organization: 0, self: 0 },
			'helping others': { department: 0, organization: 0, self: 0 },
			friendliness: { department: 0, organization: 0, self: 0 },
			influential: { department: 0, organization: 0, self: 0 },
			respectful: { department: 0, organization: 0, self: 0 },
			tolerant: { department: 0, organization: 0, self: 0 },
			'team player': { department: 0, organization: 0, self: 0 },
			collaborative: { department: 0, organization: 0, self: 0 },
			'self-awareness': { department: 0, organization: 0, self: 0 },
			empathy: { department: 0, organization: 0, self: 0 },
			initiative: { department: 0, organization: 0, self: 0 },
			conscientiousness: { department: 0, organization: 0, self: 0 },
			'self-regulation': { department: 0, organization: 0, self: 0 },
			trustworthiness: { department: 0, organization: 0, self: 0 },
			sympathy: { department: 0, organization: 0, self: 0 },
		},
	},
};
