export const initSurvey = {
	user: {
		user_name: '',
		org_name: '',
		dept_name: '',
		email: '',
		skills: {
			Initiative: { department: 0, organization: 0, self: 0 },
			'Decision-making': { department: 0, organization: 0, self: 0 },
			Prioritization: { department: 0, organization: 0, self: 0 },
			Reliability: { department: 0, organization: 0, self: 0 },
			'Active listening': { department: 0, organization: 0, self: 0 },
			Analysis: { department: 0, organization: 0, self: 0 },
			Accountability: { department: 0, organization: 0, self: 0 },
			'Analytical skills': { department: 0, organization: 0, self: 0 },
			mentorship: { department: 0, organization: 0, self: 0 },
			'inspirational abilities': { department: 0, organization: 0, self: 0 },
			'goal setting': { department: 0, organization: 0, self: 0 },
			'stress management': { department: 0, organization: 0, self: 0 },
			politeness: { department: 0, organization: 0, self: 0 },
			cooperation: { department: 0, organization: 0, self: 0 },
			reliability: { department: 0, organization: 0, self: 0 },
			'helping others': { department: 0, organization: 0, self: 0 },
			friendliness: { department: 0, organization: 0, self: 0 },
			influential: { department: 0, organization: 0, self: 0 },
			respectful: { department: 0, organization: 0, self: 0 },
			tolerant: { department: 0, organization: 0, self: 0 },
			'team player': { department: 0, organization: 0, self: 0 },
			collaborative: { department: 0, organization: 0, self: 0 },
			'self-awareness': { department: 0, organization: 0, self: 0 },
			empathy: { department: 0, organization: 0, self: 0 },
			initiative: { department: 0, organization: 0, self: 0 },
			conscientiousness: { department: 0, organization: 0, self: 0 },
			'self-regulation': { department: 0, organization: 0, self: 0 },
			trustworthiness: { department: 0, organization: 0, self: 0 },
			sympathy: { department: 0, organization: 0, self: 0 },
		},
	},
};
