export const initSurvey = {
	user: {
		user_name: '',
		org_name: '',
		dept_name: '',
		data: [
			{
				confidence: [0, 0, 0],
				'people management': [0, 0, 0],
				accountability: [0, 0, 0],
				prioritization: [0, 0, 0],
				'motivational skills': [0, 0, 0],
				coaching: [0, 0, 0],
				'project management': [0, 0, 0],
				'analytical skills': [0, 0, 0],
				creativity: [0, 0, 0],
				mentorship: [0, 0, 0],
				'inspirational abilities': [0, 0, 0],
				'goal setting': [0, 0, 0],
				'stress management': [0, 0, 0],
				politeness: [0, 0, 0],
				cooperation: [0, 0, 0],
				reliability: [0, 0, 0],
				'helping others': [0, 0, 0],
				friendliness: [0, 0, 0],
				influential: [0, 0, 0],
				respectful: [0, 0, 0],
				tolerant: [0, 0, 0],
				'team player': [0, 0, 0],
				collaborative: [0, 0, 0],
				'self awareness': [0, 0, 0],
				empathy: [0, 0, 0],
				initiative: [0, 0, 0],
				conscientiousness: [0, 0, 0],
				'self regulation': [0, 0, 0],
				trustworthiness: [0, 0, 0],
				sympathy: [0, 0, 0],
				'plan creation': [0, 0, 0],
				delegation: [0, 0, 0],
				'detail oriented': [0, 0, 0],
				punctuality: [0, 0, 0],
				'time management': [0, 0, 0],
				'resource distribution': [0, 0, 0],
				dependability: [0, 0, 0],
				adaptability: [0, 0, 0],
				'open mindedness': [0, 0, 0],
				'critical thinking': [0, 0, 0],
				patience: [0, 0, 0],
				perceptiveness: [0, 0, 0],
				'conflict resolution': [0, 0, 0],
				etiquette: [0, 0, 0],
				advocacy: [0, 0, 0],
				networking: [0, 0, 0],
				'business writing': [0, 0, 0],
				'customer service': [0, 0, 0],
				facilitation: [0, 0, 0],
				kindness: [0, 0, 0],
				respect: [0, 0, 0],
				clarity: [0, 0, 0],
				'active listening': [0, 0, 0],
				negotiation: [0, 0, 0],
				articulate: [0, 0, 0],
			},
		],
	},
};
